import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "./useAuth";

export interface AppNotification {
  id: string;
  category: "order" | "other";
  type: string;
  title: string;
  body: string | null;
  link_url: string | null;
  read_at: string | null;
  created_at: string;
}

// Two-area notification center: "order" (new order, cancellation, return,
// vendor confirmation, unconfirmed reminder - all generated by DB
// triggers/a cron job, see the notifications migration) and "other" (a
// general bucket, wired and ready, currently unpopulated). Polls rather
// than using Supabase Realtime - simplest reliable way to get "visible
// without an extra click" without adding a new moving part this pass.
export function useNotifications() {
  const { user } = useAuth();
  const [notifications, setNotifications] = useState<AppNotification[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchNotifications = useCallback(async () => {
    if (!user) {
      setNotifications([]);
      setLoading(false);
      return;
    }
    const { data, error } = await supabase
      .from("notifications")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(50);
    if (!error) setNotifications((data ?? []) as AppNotification[]);
    setLoading(false);
  }, [user]);

  useEffect(() => {
    fetchNotifications();
    const interval = setInterval(fetchNotifications, 30000);
    return () => clearInterval(interval);
  }, [fetchNotifications]);

  const markRead = async (id: string) => {
    const now = new Date().toISOString();
    setNotifications((prev) => prev.map((n) => (n.id === id ? { ...n, read_at: now } : n)));
    await supabase.from("notifications").update({ read_at: now }).eq("id", id);
  };

  const markAllRead = async (category: "order" | "other") => {
    const now = new Date().toISOString();
    const ids = notifications.filter((n) => n.category === category && !n.read_at).map((n) => n.id);
    if (ids.length === 0) return;
    setNotifications((prev) => prev.map((n) => (ids.includes(n.id) ? { ...n, read_at: now } : n)));
    await supabase.from("notifications").update({ read_at: now }).in("id", ids);
  };

  const orderNotifications = notifications.filter((n) => n.category === "order");
  const otherNotifications = notifications.filter((n) => n.category === "other");

  return {
    orderNotifications,
    otherNotifications,
    unreadOrderCount: orderNotifications.filter((n) => !n.read_at).length,
    unreadOtherCount: otherNotifications.filter((n) => !n.read_at).length,
    markRead,
    markAllRead,
    loading,
    refetch: fetchNotifications,
  };
}
