import { Link } from "react-router-dom";
import { Bell, ShoppingCart, Inbox } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { formatDistanceToNow } from "date-fns";
import { useNotifications, AppNotification } from "@/hooks/useNotifications";

function NotificationList({
  items,
  emptyLabel,
  onItemClick,
}: {
  items: AppNotification[];
  emptyLabel: string;
  onItemClick: (n: AppNotification) => void;
}) {
  if (items.length === 0) {
    return <p className="text-sm text-muted-foreground text-center py-8">{emptyLabel}</p>;
  }
  return (
    <div className="space-y-1">
      {items.map((n) => (
        <Link
          key={n.id}
          to={n.link_url || "#"}
          onClick={() => onItemClick(n)}
          className={`block p-3 rounded-lg text-sm hover:bg-muted/70 transition-colors ${
            n.read_at ? "" : "bg-primary/5"
          }`}
        >
          <div className="flex items-start justify-between gap-2">
            <p className={`font-medium ${n.read_at ? "" : "text-primary"}`}>{n.title}</p>
            {!n.read_at && <span className="h-2 w-2 rounded-full bg-primary shrink-0 mt-1.5" />}
          </div>
          {n.body && <p className="text-muted-foreground text-xs mt-0.5">{n.body}</p>}
          <p className="text-muted-foreground text-[10px] mt-1">
            {formatDistanceToNow(new Date(n.created_at), { addSuffix: true })}
          </p>
        </Link>
      ))}
    </div>
  );
}

// Two clearly separated areas per the request: Orders (new order,
// cancellation, return, confirmation, unconfirmed reminder - generated by
// DB triggers/cron, see the notifications migration) and Other (a general
// bucket for everything else). Shown for admin and vendor sessions only -
// customers don't get this bell.
export function NotificationBell() {
  const { orderNotifications, otherNotifications, unreadOrderCount, unreadOtherCount, markRead, markAllRead } =
    useNotifications();
  const totalUnread = unreadOrderCount + unreadOtherCount;

  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button variant="ghost" size="icon" className="relative">
          <Bell className="h-5 w-5" />
          {totalUnread > 0 && (
            <Badge
              variant="destructive"
              className="absolute -top-1 -right-1 h-5 min-w-5 px-1 text-[10px] flex items-center justify-center"
            >
              {totalUnread}
            </Badge>
          )}
        </Button>
      </PopoverTrigger>
      <PopoverContent align="end" className="w-96 p-0">
        <Tabs defaultValue="order">
          <TabsList className="w-full rounded-none rounded-t-md grid grid-cols-2">
            <TabsTrigger value="order" className="gap-1.5">
              <ShoppingCart className="h-3.5 w-3.5" /> Orders
              {unreadOrderCount > 0 && (
                <Badge variant="secondary" className="h-5 min-w-5 px-1 text-xs">
                  {unreadOrderCount}
                </Badge>
              )}
            </TabsTrigger>
            <TabsTrigger value="other" className="gap-1.5">
              <Inbox className="h-3.5 w-3.5" /> Other
              {unreadOtherCount > 0 && (
                <Badge variant="secondary" className="h-5 min-w-5 px-1 text-xs">
                  {unreadOtherCount}
                </Badge>
              )}
            </TabsTrigger>
          </TabsList>
          <TabsContent value="order" className="m-0 p-2">
            {unreadOrderCount > 0 && (
              <Button variant="ghost" size="sm" className="w-full text-xs" onClick={() => markAllRead("order")}>
                Mark all read
              </Button>
            )}
            <ScrollArea className="max-h-80">
              <NotificationList
                items={orderNotifications}
                emptyLabel="No order notifications yet."
                onItemClick={(n) => !n.read_at && markRead(n.id)}
              />
            </ScrollArea>
          </TabsContent>
          <TabsContent value="other" className="m-0 p-2">
            {unreadOtherCount > 0 && (
              <Button variant="ghost" size="sm" className="w-full text-xs" onClick={() => markAllRead("other")}>
                Mark all read
              </Button>
            )}
            <ScrollArea className="max-h-80">
              <NotificationList
                items={otherNotifications}
                emptyLabel="No other notifications yet."
                onItemClick={(n) => !n.read_at && markRead(n.id)}
              />
            </ScrollArea>
          </TabsContent>
        </Tabs>
      </PopoverContent>
    </Popover>
  );
}
